test : ci/cd test

diff --git a/.github/workflows/cd-fe.yml b/.github/workflows/cd-fe.yml
--- a/.github/workflows/cd-fe.yml
+++ b/.github/workflows/cd-fe.yml
@@ -126,8 +126,8 @@ jobs:
           INSTANCE_IPS: ${{ steps.get-instances.outputs.instance-ips }}
           INSTANCE_IDS: ${{ steps.get-instances.outputs.instance-ids }}
           TG_ARN: ${{ steps.get-instances.outputs.tg-arn }}
-          NEXT_PUBLIC_API_URL: ${{ env.NEXT_PUBLIC_API_URL }}
-          NEXT_PUBLIC_SOCKET_URL: ${{ env.NEXT_PUBLIC_SOCKET_URL }}
+          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
+          NEXT_PUBLIC_SOCKET_URL: ${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
         run: |
           echo "🚀 Starting deployment..."
 
@@ -156,8 +156,13 @@ jobs:
               ENV_FILE=".env.local"
               touch $ENV_FILE
               
-              echo "API_URL=${NEXT_PUBLIC_API_URL}" >> $ENV_FILE
-              echo "SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}" >> $ENV_FILE
+              echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" >> $ENV_FILE
+              echo "NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}" >> $ENV_FILE
+              
+              if ! grep -q "NEXT_PUBLIC_API_URL" "$ENV_FILE"; then
+              echo "❌ Error: NEXT_PUBLIC_API_URL not found in environment file"
+              exit 1
+              fi
               
               echo "📄  Environment file created:"
               cat $ENV_FILE
